const STATUS_IN_PROGRESS = "IN PROGRESS";
const STATUS_COMPLETED = "COMPLETED";

const MESSAGE_STATUS_PENDING = "PENDING";
const MESSAGE_STATUS_FAILED = "FAILED";
const MESSAGE_STATUS_VERIFIED = "VERIFIED";

export {
  STATUS_IN_PROGRESS,
  STATUS_COMPLETED,
  MESSAGE_STATUS_PENDING,
  MESSAGE_STATUS_FAILED,
  MESSAGE_STATUS_VERIFIED,
};
