import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flowbite } from "flowbite-react";

import CorbadoProvider from "@/utils/corbado/Provider";
import FlowbiteTheme from "./theme";
import { SupabaseSessionProvider } from "@/components/Context/SupabaseSessionProvider";

import "./globals.css";
import { createClient } from "@/utils/supabase/server";
import { AuthSession, Session, UserResponse } from "@supabase/supabase-js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const session = await supabase.auth.getSession();

  const response = await fetch(
    `http://localhost:3000/api/user/${session?.data?.session?.user?.id}`,
    {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
      next: {
        tags: ["user_info"],
        revalidate: 0,
      },
    }
  );

  if (!response.ok) {
    throw new Error(`Failed to fetch user ${session?.data?.session?.user?.id}`);
  }

  const data = await response.json();

  return (
    <html lang="en">
      <CorbadoProvider>
        <Flowbite theme={{ theme: FlowbiteTheme }}>
          <SupabaseSessionProvider
            userInfo={data}
            session={session?.data?.session as Session}
          >
            <body className={inter.className}>
              <main className="bg-gray-200">{children}</main>
            </body>
          </SupabaseSessionProvider>
        </Flowbite>
      </CorbadoProvider>
    </html>
  );
}
